const { EmbedBuilder, AttachmentBuilder } = require('discord.js');
const { embedColor, embedAuthorName } = require('../config.json');

class SherbertBotEmbedErrorPage {
	constructor(errorName, errorCode, errorMsg, interaction) {
		const errorIconFile = new AttachmentBuilder('../res/imgs/erroricon.png')
		const errorEmbed = new EmbedBuilder()
			.setColor(embedColor)
			.setTitle('Bug Report')
			.setAuthor({ name: 'SherbertBot' })
			.setDescription('Were sorry, but a error occured, please try again later, heres is some log info')
			.setThumbnail('attachment://erroricon.png')
			.addFields(
				{ name: 'Error name', value: `${errorName}` },
				{ name: 'Error code', value: `${errorCode}` },
				{ name: 'Error message', value: `${errorMsg}` },
				{ name: 'SherbertBot Version', value: '1.0.0 Alpha' },
			)
			.setTimestamp()
			.setFooter({ text: 'Generated by SherbertBot Version 1.0.0' });

		//todo: check if the interaction is repliable
		await interaction.reply({ embeds: [errorEmbed], files: [errorIconFile], ephemeral: true });
		
		return errorEmbed;
	}
}
exports.SherbertBotEmbedErrorPage = SherbertBotEmbedErrorPage;
